subscription_id: "9c586efc-2916-46e3-a00a-7a003f986647"
resource_group: "yondu_gnm_resource_group"
workspace_name: "yondu_gnm_workspace"
# compute_name: "cluster-distributed-gpu-simple"
compute_name: "a100-gpu"
# experiment_name: "yondu_gnm_aml_distributed"
conda_path: "./conda.yml"
environment_name: "new_lerobot_env"
# conda_path: Path(Path(__file__).parent, "conda.yml")
# code_path: Path(Path(__file__).parent.parent)
# model_name: "stablenav-distributed"

