metadata:
  description: "ACT Policy on 500 episodes: 
  Task Descroption: (Put orange and bannana orange datasets combined), 
  Variations: Objects: (Positions of orange changed), Robot positions: No, Camera positions: No
  Camera: Wrist and overhead"
  author: "Aravindh"
  date: "2025-04-12"
  status: "planned"
  dataset_name: "trossen_orange_500_merged_1cam"
  results:
    success_rate: ""
    convergence_time: ""
    notes: ""

parameters:
  dataset:
    repo_id: "null"
    
  policy:
    type: "act"
    device: "cuda"
    use_amp: true
    n_obs_steps: 1


  num_workers: 8    
  batch_size: 8
  steps: 200000
  job_name: "trossen_put_orange_run_9"
    
  wandb:
    project: "lerobot"