metadata:
  description: "ACT Policy with Wrist Camera Only: 
  Task Description: Pick tshirts using only wrist camera view, using same 3 datasets as original
  Variations: Objects: (Positions of tshirts changed), Robot positions: No, Camera positions: No
  Camera: Wrist only"
  author: "Aravindh"
  date: "2025-05-02"
  status: "planned"
  dataset_name: "trossen_pick_tshirt_3cam_v2m5"
  results:
    success_rate: ""
    convergence_time: ""
    notes: ""

parameters:
  dataset:
    repo_id: "Aravindh25/trossen_pick_tshirt_3cam_v2m5"
    
  policy:
    type: "act"
    device: "cuda"
    use_amp: true
    n_obs_steps: 1
    input_features: "'{\"observation.images.cam_wrist\": {\"type\": \"VISUAL\", \"shape\": [3, 480, 640]}, \"observation.state\": {\"type\": \"STATE\", \"shape\": [7]}}'"
    output_features: "'{\"action\": {\"type\": \"ACTION\", \"shape\": [7]}}'"

  num_workers: 8   
  batch_size: 8
  steps: 100000
  job_name: "trossen_pick_tshirts_1cam_wrist_only"
    
  wandb:
    project: "lerobot" 